### ISSUE TITLE
Where is the .cleancase command or the releases tab?

### ISSUE THREAD

**Issue by RyanMcCarl** [paultopia/cleanup-case#1]
Hi there, I am very interested in this project, but the instructions in your README do not seem to match the files available. How can I get this running to try it?

```
ryan@Ryans-Air ~/dev/lawgraph/src/cleanup-case ±master⚡ » ~/dev/lawgraph/src/cleanup-case/process-rtfs.sh halliburton-test.rtf
/Users/ryan/dev/lawgraph/src/cleanup-case/process-rtfs.sh: line 4: ./cleancase: No such file or directory
ryan@Ryans-Air ~/dev/lawgraph/src/cleanup-case ±master⚡ »
```

Thank you,
Ryan

**Comment by paultopia** [comment]
Hi!  It looks like you cloned/downloaded the source and are trying to run from there. 

For the executable file, what you'll want to do is, if you go to the home page of the repository, right above the row where the clone or download button is, you'll see a row of items like '23 commits', '1 branch' '2 releases' and so forth.  If you click on releases there, it'll open the releases tab.  Then you'll see the executable file (as the first thing to download in the most recent release.) 

If you save that file, plus the shell script you already have from the source, in the directory that has your rtf files, and make sure they're executable, then it should work!

**Comment by RyanMcCarl** [comment]
Got it, thanks! I was looking for releases on the top row of Github tabs.

**Comment by RyanMcCarl** [comment]
Still having trouble but it's a distinct issue so I'll close this one.
